import va_gen as va

# input template file path
template_path ='./template.va'
# output file path
# save_path = './generate.va'

# the comment in the veriloga file
comment = 'This file is generated by the VA_GEN .'
# the module name
module_name = 'macro_write_wave_gen'

# add today date, and the version number in the output file name

from datetime import datetime
today = datetime.today().strftime('%Y%m%d')
save_path_v1 = f'./vaoutput/{module_name}_{today}_v1.va'
save_path_v2 = f'./vaoutput/{module_name}_{today}_v2.va'

Num_opt =16
clk_number = 8
clk_cycle = [0,0,0,0,1,1,1,1]
WR_EN_cycle = [0,1,1,1,1,1,1,1]
W1 = 8*[0]+8*[1]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]
W2 = 8*[0]+8*[0]+8*[1]+8*[0]+8*[0]+8*[1]+8*[0]+8*[0]
W3 = 8*[0]+8*[0]+8*[0]+8*[1]+8*[0]+8*[1]+8*[0]+8*[1]
W4 = 8*[0]+8*[0]+8*[0]+8*[0]+8*[1]+8*[0]+8*[0]+8*[1]
W5 = 8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[1]+8*[0]
W0 = 8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]
WWL = 8*[0]+8*[1]+8*[2]+8*[3]+8*[4]+8*[5]+8*[6]+8*[7]+8*[8]+8*[9]+8*[10]+8*[11]+8*[12]+8*[13]+8*[14]+8*[15]

PLCE_cycle = [0,0,1,1,1,1,1,1]
PRE_cycle = WR_EN_cycle
HRWLE_cycle = 8*[0]
LRWLE_cycle = 8*[0]

wl_mask = (1 << 64) - 1 #EXPLAIN: 计算WL的掩码，确保WL的值在0到Num_opt-1之间
RWL = [wl_mask ^ w for w in WWL]

GND_cycle = 8*[0]
VDD_cycle = 8*[1]           
           

# the expected output signals 
# signal-name | signal-width | waves-length | waves-value 
signal_args = [
    ['W1<63:0>', 1, Num_opt*clk_number, W1*2],
    ['W2<63:0>', 1, Num_opt*clk_number, W2*2],
    ['W3<63:0>', 1, Num_opt*clk_number, W3*2],
    ['W4<63:0>', 1, Num_opt*clk_number, W4*2],
    ['W5<63:0>', 1, Num_opt*clk_number, W5*2],
    ['W0<63:0>', 1, Num_opt*clk_number, W0*2],
    ['WR_EN', 1, Num_opt*clk_number, Num_opt*WR_EN_cycle],
    ['CLK', 1, Num_opt*clk_number, Num_opt*clk_cycle],
    ['E2', 1, Num_opt*clk_number, Num_opt//2*VDD_cycle + Num_opt//2*GND_cycle],  # 先low 再high
    ['E6', 1, Num_opt*clk_number, Num_opt//2*VDD_cycle + Num_opt//2*GND_cycle],
    ['PLCE', 1, Num_opt*clk_number, Num_opt*PLCE_cycle],
    ['PRE', 1, Num_opt*clk_number, Num_opt*PRE_cycle],
    ['HRWLE', 1, Num_opt*clk_number, Num_opt//2*GND_cycle + Num_opt//2*VDD_cycle], 
    ['LRWLE', 1, Num_opt*clk_number, Num_opt//2*VDD_cycle + Num_opt//2*GND_cycle],

    ['WWL<63:0>', 64, Num_opt*clk_number, WWL],
    ['RWL<63:0>', 64, Num_opt*clk_number, RWL],
    
    
    
    
    
    ['INT', 1, Num_opt*clk_number, GND_cycle*Num_opt],
    ['CDS_EN', 1, Num_opt*clk_number, GND_cycle*Num_opt],
    
    
    # ['precharge', 1, 4, [0, 1, 0, 1]],
]

# port_groups = {
#     'signal': ['signal_2', 'signal_1']
# }

if __name__ == '__main__':
    generator = va.VaGenerator(template_path)
    generator.generate_veriloga(module_name, comment, signal_args, save_path_v1, port_groups=None)
    # generator.generate_veriloga(module_name, comment, signal_args, save_path_v2, port_groups=port_groups)