import va_gen as va

# input template file path
template_path ='./template.va'
# output file path
# save_path = './generate.va'

# the comment in the veriloga file
comment = 'This file is generated by the VA_GEN .'
# the module name
module_name = 'Va_TimeGen_1'

# add today date, and the version number in the output file name

from datetime import datetime
today = datetime.today().strftime('%Y%m%d')
save_path_v1 = f'./vaoutput/{module_name}_{today}_v1.va'
save_path_v2 = f'./vaoutput/{module_name}_{today}_v2.va'


# the expected output signals 
# signal-name | signal-width | waves-length | waves-value 
signal_args = [
    ['signal_1', 8, 4, [0, 1, 2, 3]],
    ['signal_2', 1, 4, [0, 1, 0, 1]],
    ['precharge', 1, 4, [0, 1, 0, 1]],
]

port_groups = {
    'signal': ['signal_2', 'signal_1']
}

if __name__ == '__main__':
    generator = va.VaGenerator(template_path)
    generator.generate_veriloga(module_name, comment, signal_args, save_path_v1, port_groups=None)
    generator.generate_veriloga(module_name, comment, signal_args, save_path_v2, port_groups=port_groups)