import va_gen as va

# input template file path
template_path ='./template.va'
# output file path
# save_path = './generate.va'

# the comment in the veriloga file
comment = 'This file is generated by the VA_GEN .'
# the module name
module_name = 'macro_write_wave_gen'

# add today date, and the version number in the output file name

from datetime import datetime
today = datetime.today().strftime('%Y%m%d')
save_path_v1 = f'./vaoutput/{module_name}_{today}_v1.va'
save_path_v2 = f'./vaoutput/{module_name}_{today}_v2.va'

Num_opt =16
clk_number = 8
clk_cycle = [0,0,0,0,1,1,1,1]
WR_EN_cycle = [0,1,1,1,1,1,1,1]
W1 = 8*[0]+8*[1]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]
W2 = 8*[0]+8*[0]+8*[1]+8*[0]+8*[0]+8*[1]+8*[0]+8*[0]
W3 = 8*[0]+8*[0]+8*[0]+8*[1]+8*[0]+8*[1]+8*[0]+8*[1]
W4 = 8*[0]+8*[0]+8*[0]+8*[0]+8*[1]+8*[0]+8*[0]+8*[1]
W5 = 8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[1]+8*[0]
W0 = 8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]+8*[0]
WWL = 8*[1]+8*[1<<1]+8*[1<<2]+8*[1<<3]+8*[1<<4]+8*[1<<5]+8*[1<<6]+8*[1<<7]+8*[1<<8]+8*[1<<9]+8*[1<<10]+8*[1<<11]+8*[1<<12]+8*[1<<13]+8*[1<<14]+8*[1<<15]

PRE_cycle = [1,0,0,0,0,0,0,0]
HRWLE_cycle = 8*[0]
LRWLE_cycle = 8*[0]

wl_mask = (1 << 64) - 1 #EXPLAIN: 计算WL的掩码，确保WL的值在0到Num_opt-1之间

def build_rwl_patterns(group_count, repeat_per_group, width=64):
    mask = (1 << width) - 1
    patterns = []

    low_width = max(repeat_per_group - 1, 0)
    high_width = repeat_per_group - low_width

    for bit_idx in range(group_count):
        # 每组 repeat_per_group 个采样点：先低脉冲，再回到高电平
        # 这里对应 8 点时序为 7 个 0 + 1 个 1（对选中的 bit）。
        low_value = mask & ~(1 << bit_idx)
        high_value = mask
        patterns.extend([low_value] * low_width + [high_value] * high_width)
    return patterns

RWL = build_rwl_patterns(Num_opt, clk_number)

def build_plce_from_wwl_falling(wwl_values, width=64, pulse_width=2):
    mask = (1 << width) - 1
    plce_values = [mask] * len(wwl_values)

    for t in range(1, len(wwl_values)):
        prev = int(wwl_values[t - 1])
        curr = int(wwl_values[t])
        falling_bits = prev & (~curr)

        if falling_bits == 0:
            continue

        for bit in range(width):
            if ((falling_bits >> bit) & 1) == 0:
                continue
            for k in range(pulse_width):
                # Place a 2-sample low pulse centered around the falling edge.
                idx = (t - 1) + k
                if 0 <= idx < len(plce_values):
                    plce_values[idx] &= ~(1 << bit)

    return plce_values

PLCE = build_plce_from_wwl_falling(WWL, width=64, pulse_width=2)

GND_cycle = 8*[0]
VDD_cycle = 8*[1]           
           

# the expected output signals 
# signal-name | signal-width | waves-length | waves-value 
signal_args = [
    ['W1', 1, Num_opt*clk_number, W1*2],
    ['W2', 1, Num_opt*clk_number, W2*2],
    ['W3', 1, Num_opt*clk_number, W3*2],
    ['W4', 1, Num_opt*clk_number, W4*2],
    ['W5', 1, Num_opt*clk_number, W5*2],
    ['W0', 1, Num_opt*clk_number, W0*2],
    ['WR_EN', 1, Num_opt*clk_number, Num_opt*WR_EN_cycle],
    ['CLK_OUT', 1, Num_opt*clk_number, Num_opt*clk_cycle],
    ['E2', 1, Num_opt*clk_number, Num_opt//2*VDD_cycle + Num_opt//2*GND_cycle],  # 先low 再high
    ['E6', 1, Num_opt*clk_number, Num_opt//2*VDD_cycle + Num_opt//2*GND_cycle],
    ['PLCE', 64, Num_opt*clk_number, PLCE],
    ['PRE', 1, Num_opt*clk_number, Num_opt*PRE_cycle],
    ['HRWLE', 1, Num_opt*clk_number, Num_opt//2*GND_cycle + Num_opt//2*VDD_cycle], 
    ['LRWLE', 1, Num_opt*clk_number, Num_opt//2*VDD_cycle + Num_opt//2*GND_cycle],

    ['WWL', 64, Num_opt*clk_number, WWL],
    ['RWL', 64, Num_opt*clk_number, RWL],
    
    
    
    

    ['CE', 1, Num_opt*clk_number, GND_cycle*Num_opt],
    ['INT', 1, Num_opt*clk_number, GND_cycle*Num_opt],
    ['CDS_EN', 1, Num_opt*clk_number, GND_cycle*Num_opt],
    
    
    # ['precharge', 1, 4, [0, 1, 0, 1]],
]

# port_groups = {
#     'signal': ['signal_2', 'signal_1']
# }

if __name__ == '__main__':
    generator = va.VaGenerator(template_path)
    generator.generate_veriloga(module_name, comment, signal_args, save_path_v1, port_groups=None)
    # generator.generate_veriloga(module_name, comment, signal_args, save_path_v2, port_groups=port_groups)